name: Build Docker with Java and deploy to registry

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: |
        printf "${{ secrets.SETTINGS_SECURITY_XML }}" > ~/.m2/settings-security.xml
        printf "${{ secrets.SETTINGS_XML }}" > ~/.m2/settings.xml
        mvn package
    - uses: actions/upload-artifact@v1
      with:
       name: BortexelBot
       path: target/
  deploy:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/download-artifact@v1
      with:
          name: BortexelBot
          path: target/
    - name: Build, tag, and push Docker image to registry
      id: build-image
      run: |
        docker login -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_PASSWORD }} registry.ruscalworld.ru
        docker build -t registry.ruscalworld.ru/ruscalworld/bortexelbot .
        docker push registry.ruscalworld.ru/ruscalworld/bortexelbot
